# Generated by Django 2.1.5 on 2020-06-10 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200610_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('user', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='voting',
            index_together={('user', 'product')},
        ),
    ]
